-- run against Workplace
exec spPTIPurgeTableData 'COMPANY',1,1
select * from APVendor
select * from WCTax

go  
ALTER PROCEDURE spPTIPurgeTableData  
 @xDatabase  VARCHAR(60)  = null  -- CONTROL, COMPANY, PTIMaster  
,@xPurgeSetup INT    = 0  -- If set to 1 then the setup tables will be cleared as well.  
,@xOutputOnly INT    = 0  -- If set to 1 then the truncate statements will be returned only.  
,@xModule  VARCHAR(255) = null -- AP,AR,BUD,CAT,EXP,GL,IFC,IV,PA,PM,PO,PTI,RCV,RFQ,RQ,TE,VC,WC   
AS  
DECLARE  
 @strDatabase VARCHAR(60)  
,@strTableName NVARCHAR(80)  
,@strMessage VARCHAR(256)  
,@strSQL  NVARCHAR(4000)  
,@strPhysicalDB NVARCHAR(256)  
,@nFound  INT  
--  
SET NOCOUNT ON  
--  
IF(UPPER(@xDatabase) = 'CONTROL')  
 SELECT @strDatabase='CONTROL' , @strPhysicalDB = idfControlDB FROM vwFNACompany  
ELSE IF(UPPER(@xDatabase) = 'PTIMASTER')  
 SELECT @strDatabase='PTIMaster' , @strPhysicalDB ='PTIMaster'  
ELSE  
 SELECT @strDatabase='COMPANY' , @strPhysicalDB = DB_NAME()  
  
DECLARE curWCDataObject INSENSITIVE CURSOR FOR   
SELECT idfTableName  
FROM dbo.WCDataObject D WITH (NOLOCK)  
WHERE idfDatabase = @strDatabase  
 AND (  
   (@xPurgeSetup = 0 AND idfType IN ('Tran','Work'))  
  OR  
   (@xPurgeSetup = 1)  
  )  
 AND (@xModule IS NULL OR D.idfModule='::'+@xModule+'::')  
ORDER BY idfTableName  
  
OPEN curWCDataObject  
   
FETCH NEXT FROM curWCDataObject INTO @strTableName  
WHILE (@@fetch_status <> -1)  
BEGIN  
 IF (@@fetch_status <> -2)  
 BEGIN  
  SET @nFound=0
  SELECT @strSQL = 'SELECT @nFound=1 FROM '+@strPhysicalDB+'..sysobjects WHERE name='''+@strTableName+''''  
  
  EXEC sp_executesql @strSQL,N'@nFound INT OUTPUT',@nFound OUTPUT  
  
  IF(@xOutputOnly=0) BEGIN  
     
   IF(@nFound=1) BEGIN  
    SELECT @strMessage = 'Truncating Table: ' + @strPhysicalDB+'..'+@strTableName  
    PRINT @strMessage  
  
    SELECT @strSQL = 'TRUNCATE TABLE '+@strPhysicalDB+'..'+@strTableName  
    EXECUTE (@strSQL)  
	
   END  
   ELSE BEGIN  
    SELECT @strMessage = 'Could not find table: ' + @strPhysicalDB+'..'+@strTableName  
    PRINT @strMessage  
   END  
  END  
  ELSE BEGIN  
   IF(@nFound=1) BEGIN  
    SELECT @strMessage = 'TRUNCATE TABLE '+@strTableName  
	--EXECUTE (@strSQL)  
    PRINT @strMessage  
   END  
  END  
 END  
 FETCH NEXT FROM curWCDataObject INTO @strTableName  
END  
   
CLOSE curWCDataObject  
DEALLOCATE curWCDataObject  
  
IF(@xOutputOnly=0)   
 EXEC dbo.spPTIFixCalcTable 'UPDATE'  
ELSE BEGIN  
 SELECT @strMessage = 'EXEC dbo.spPTIFixCalcTable ''UPDATE'''  
 PRINT @strMessage  
END  
  
RETURN(0)

TRUNCATE TABLE APAddress
TRUNCATE TABLE APAddressPortal
TRUNCATE TABLE APAutoPaymentBatch
TRUNCATE TABLE APAutoPaymentBatchHist
TRUNCATE TABLE APAutoPaymentDtl
TRUNCATE TABLE APAutoPaymentDtlApply
TRUNCATE TABLE APAutoPaymentDtlApplyHist
TRUNCATE TABLE APAutoPaymentDtlHist
TRUNCATE TABLE APAutoPaymentHdr
TRUNCATE TABLE APAutoPaymentHdrHist
TRUNCATE TABLE APInvoicePortalDtl
TRUNCATE TABLE APInvoicePortalHdr
TRUNCATE TABLE APInvoicePortalHdrAttach
TRUNCATE TABLE APInvoicePortalHdrWCSecurity
TRUNCATE TABLE APPaymentDtl
TRUNCATE TABLE APPaymentDtlApply
TRUNCATE TABLE APPaymentDtlApplyHist
TRUNCATE TABLE APPaymentDtlHist
TRUNCATE TABLE APPaymentHdr
TRUNCATE TABLE APPaymentHdrHist
TRUNCATE TABLE APPaymentJournal
TRUNCATE TABLE APTaxType
TRUNCATE TABLE APTaxTypeDtl
TRUNCATE TABLE APVendor
TRUNCATE TABLE APVendorAprDtl
TRUNCATE TABLE APVendorAprDtlHist
TRUNCATE TABLE APVendorAprHdr
TRUNCATE TABLE APVendorAprHdrHist
TRUNCATE TABLE APVendorClass
TRUNCATE TABLE APVendorClassTaxClass
TRUNCATE TABLE APVendorCommodity
TRUNCATE TABLE APVendorLog
TRUNCATE TABLE APVendorPortal
TRUNCATE TABLE APVendorPortalAttach
TRUNCATE TABLE APVendorPortalUser
TRUNCATE TABLE APVendorSession
TRUNCATE TABLE APVendorSiteAccount
TRUNCATE TABLE APVendorTaxClass
TRUNCATE TABLE APVoucher
TRUNCATE TABLE APVoucherDtl
TRUNCATE TABLE APVoucherDtlAppliedCM
TRUNCATE TABLE APVoucherDtlDistribution
TRUNCATE TABLE APVoucherDtlSegment
TRUNCATE TABLE APVoucherDtlTax
TRUNCATE TABLE APVoucherJournal
TRUNCATE TABLE APVoucherPayment
TRUNCATE TABLE ARCustomer
TRUNCATE TABLE ARCustomerAddress
TRUNCATE TABLE ARCustomerClass
TRUNCATE TABLE ARInvoiceDtl
TRUNCATE TABLE ARInvoiceHdr
TRUNCATE TABLE ARSession
TRUNCATE TABLE BUDHeader
TRUNCATE TABLE BUDPeriod
TRUNCATE TABLE CATCart
TRUNCATE TABLE CATCartItem
TRUNCATE TABLE CATCatalog
TRUNCATE TABLE CATCatalogAccess
TRUNCATE TABLE CATCatalogCategory
TRUNCATE TABLE CATCatalogVendor
TRUNCATE TABLE CATCategory
TRUNCATE TABLE CATExcludedWord
TRUNCATE TABLE CATItem
TRUNCATE TABLE CATItemCategory
TRUNCATE TABLE CATItemImage
TRUNCATE TABLE CATKeyword
TRUNCATE TABLE CATShopList
TRUNCATE TABLE CATShopListItem
TRUNCATE TABLE EXPAprDtl
TRUNCATE TABLE EXPAprDtlAttendee
TRUNCATE TABLE EXPAprDtlAttendeeHist
TRUNCATE TABLE EXPAprDtlDistribution
TRUNCATE TABLE EXPAprDtlDistributionHist
TRUNCATE TABLE EXPAprDtlEXPExpenseSheetHdr
TRUNCATE TABLE EXPAprDtlEXPTypeQuestionnaire
TRUNCATE TABLE EXPAprDtlHist
TRUNCATE TABLE EXPAprDtlHistEXPExpenseSheetHdrHist
TRUNCATE TABLE EXPAprDtlHistEXPTypeQuestionnaire
TRUNCATE TABLE EXPAprDtlProjectDistribution
TRUNCATE TABLE EXPAprDtlProjectDistributionHist
TRUNCATE TABLE EXPAprDtlSegment
TRUNCATE TABLE EXPAprDtlSegmentHist
TRUNCATE TABLE EXPAprDtlSplit
TRUNCATE TABLE EXPAprDtlSplitAttendee
TRUNCATE TABLE EXPAprDtlSplitAttendeeHist
TRUNCATE TABLE EXPAprDtlSplitHist
TRUNCATE TABLE EXPAprDtlSplitProjectDistribution
TRUNCATE TABLE EXPAprDtlSplitProjectDistributionHist
TRUNCATE TABLE EXPAprDtlSplitSegment
TRUNCATE TABLE EXPAprDtlSplitSegmentHist
TRUNCATE TABLE EXPAprDtlSplitTax
TRUNCATE TABLE EXPAprDtlSplitTaxHist
TRUNCATE TABLE EXPAprDtlTax
TRUNCATE TABLE EXPAprDtlTaxHist
TRUNCATE TABLE EXPAprHdr
TRUNCATE TABLE EXPAprHdrHist
TRUNCATE TABLE EXPAttendeeExpCategory
TRUNCATE TABLE EXPAttendeeExpProduct
TRUNCATE TABLE EXPAttendeeExpType
TRUNCATE TABLE EXPCreditCard
TRUNCATE TABLE EXPCreditCardHist
TRUNCATE TABLE EXPEvent
TRUNCATE TABLE EXPExpenseSheetDtl
TRUNCATE TABLE EXPExpenseSheetDtlAttendee
TRUNCATE TABLE EXPExpenseSheetDtlAttendeeHist
TRUNCATE TABLE EXPExpenseSheetDtlDistribution
TRUNCATE TABLE EXPExpenseSheetDtlDistributionHist
TRUNCATE TABLE EXPExpenseSheetDtlEXPTypeQuestionnaire
TRUNCATE TABLE EXPExpenseSheetDtlHist
TRUNCATE TABLE EXPExpenseSheetDtlHistEXPTypeQuestionnaire
TRUNCATE TABLE EXPExpenseSheetDtlLog
TRUNCATE TABLE EXPExpenseSheetDtlLogHist
TRUNCATE TABLE EXPExpenseSheetDtlProjectDistribution
TRUNCATE TABLE EXPExpenseSheetDtlProjectDistributionHist
TRUNCATE TABLE EXPExpenseSheetDtlSegment
TRUNCATE TABLE EXPExpenseSheetDtlSegmentHist
TRUNCATE TABLE EXPExpenseSheetDtlSplit
TRUNCATE TABLE EXPExpenseSheetDtlSplitAttendee
TRUNCATE TABLE EXPExpenseSheetDtlSplitAttendeeHist
TRUNCATE TABLE EXPExpenseSheetDtlSplitHist
TRUNCATE TABLE EXPExpenseSheetDtlSplitLog
TRUNCATE TABLE EXPExpenseSheetDtlSplitProjectDistribution
TRUNCATE TABLE EXPExpenseSheetDtlSplitProjectDistributionHist
TRUNCATE TABLE EXPExpenseSheetDtlSplitSegment
TRUNCATE TABLE EXPExpenseSheetDtlSplitSegmentHist
TRUNCATE TABLE EXPExpenseSheetDtlSplitTax
TRUNCATE TABLE EXPExpenseSheetDtlSplitTaxHist
TRUNCATE TABLE EXPExpenseSheetDtlTax
TRUNCATE TABLE EXPExpenseSheetDtlTaxHist
TRUNCATE TABLE EXPExpenseSheetHdr
TRUNCATE TABLE EXPExpenseSheetHdrHist
TRUNCATE TABLE EXPMAPAddress
TRUNCATE TABLE EXPMileageDtl
TRUNCATE TABLE EXPMileageDtlHist
TRUNCATE TABLE EXPMileageHdr
TRUNCATE TABLE EXPMileageHdrHist
TRUNCATE TABLE EXPMobileExpense
TRUNCATE TABLE EXPNPI
TRUNCATE TABLE EXPPayment
TRUNCATE TABLE EXPRevDtl
TRUNCATE TABLE EXPRevHdr
TRUNCATE TABLE EXPSession
TRUNCATE TABLE EXPType
TRUNCATE TABLE EXPTypeCountry
TRUNCATE TABLE EXPTypeQuestionnaire
TRUNCATE TABLE GLAccount
TRUNCATE TABLE GLAccountGroup
TRUNCATE TABLE GLBudgetActual
TRUNCATE TABLE GLBudgetActualTrx
TRUNCATE TABLE GLBudgetDtl
TRUNCATE TABLE GLBudgetDtlHdr
TRUNCATE TABLE GLBudgetDtlTrx
TRUNCATE TABLE GLBudgetHdr
TRUNCATE TABLE GLJournalDtl
TRUNCATE TABLE GLJournalHdr
TRUNCATE TABLE GLJournalSummary
TRUNCATE TABLE GLJournalType
TRUNCATE TABLE GLPeriod
TRUNCATE TABLE GLPostCodeAccountCombination
TRUNCATE TABLE GLPostCodeAccountDtl
TRUNCATE TABLE GLPostCodeAccountHdr
TRUNCATE TABLE GLPostCodeDtl
TRUNCATE TABLE GLPostCodeHdr
TRUNCATE TABLE GLPostCodeType
TRUNCATE TABLE GLReference
TRUNCATE TABLE GLReferenceType
TRUNCATE TABLE GLReferenceTypeAccount
TRUNCATE TABLE GLSegmentDtl
TRUNCATE TABLE GLSegmentDtlCombination
TRUNCATE TABLE GLSegmentDtlCombinationTree
TRUNCATE TABLE GLSegmentDtlEAICWork
TRUNCATE TABLE GLSegmentHdr
TRUNCATE TABLE GLSegmentHdrCombination
TRUNCATE TABLE GLSegmentIC
TRUNCATE TABLE IFC_PAFNATrack
TRUNCATE TABLE IFC_PAGLImport
TRUNCATE TABLE IVAdjustmentDtl
TRUNCATE TABLE IVAdjustmentHdr
TRUNCATE TABLE IVCommodity
TRUNCATE TABLE IVCostLayerAdjDtl
TRUNCATE TABLE IVCostLayerAdjDtlHist
TRUNCATE TABLE IVCostLayerAdjHdr
TRUNCATE TABLE IVCostLayerAdjHdrHist
TRUNCATE TABLE IVItem
TRUNCATE TABLE IVItemGroup
TRUNCATE TABLE IVItemGroupSegment
TRUNCATE TABLE IVItemGroupTaxClass
TRUNCATE TABLE IVItemManufacturer
TRUNCATE TABLE IVItemPrecision
TRUNCATE TABLE IVItemSite
TRUNCATE TABLE IVItemSiteAccount
TRUNCATE TABLE IVItemSiteStock
TRUNCATE TABLE IVItemSiteStockAllocated
TRUNCATE TABLE IVItemSiteStockHist
TRUNCATE TABLE IVItemSiteStockWork
TRUNCATE TABLE IVItemTaxClass
TRUNCATE TABLE IVItemVendor
TRUNCATE TABLE IVJournal
TRUNCATE TABLE IVJournalItemSiteStockConsumed
TRUNCATE TABLE IVPhysicalDtl
TRUNCATE TABLE IVPhysicalDtlHist
TRUNCATE TABLE IVPhysicalHdr
TRUNCATE TABLE IVPhysicalHdrHist
TRUNCATE TABLE IVPhysicalSerialLot
TRUNCATE TABLE IVPhysicalSerialLotHist
TRUNCATE TABLE IVPickList
TRUNCATE TABLE IVSite
TRUNCATE TABLE IVSiteAccount
TRUNCATE TABLE IVStockAdjustmentDtl
TRUNCATE TABLE IVStockAdjustmentDtlDistribution
TRUNCATE TABLE IVStockAdjustmentDtlDistributionHist
TRUNCATE TABLE IVStockAdjustmentDtlHist
TRUNCATE TABLE IVStockAdjustmentHdr
TRUNCATE TABLE IVStockAdjustmentHdrHist
TRUNCATE TABLE IVStockAdjustmentReason
TRUNCATE TABLE IVStockAdjustmentType
TRUNCATE TABLE IVTransferDtl
TRUNCATE TABLE IVTransferDtlDistribution
TRUNCATE TABLE IVTransferDtlDistributionHist
TRUNCATE TABLE IVTransferDtlHist
TRUNCATE TABLE IVTransferDtlItemSiteStockAllocated
TRUNCATE TABLE IVTransferDtlItemSiteStockAllocatedHist
TRUNCATE TABLE IVTransferDtlPO
TRUNCATE TABLE IVTransferDtlPOHist
TRUNCATE TABLE IVTransferHdr
TRUNCATE TABLE IVTransferHdrHist
TRUNCATE TABLE IVUOM
TRUNCATE TABLE IVUOMConversionGroupDtl
TRUNCATE TABLE IVUOMConversionGroupHdr
TRUNCATE TABLE PAAccess
TRUNCATE TABLE PAAccount
TRUNCATE TABLE PAAccountType
TRUNCATE TABLE PAAccountTypeAccess
TRUNCATE TABLE PAActivity
TRUNCATE TABLE PAActivityCategory
TRUNCATE TABLE PAActualTrx
TRUNCATE TABLE PAAprDtl
TRUNCATE TABLE PAAprDtlHist
TRUNCATE TABLE PAAprHdr
TRUNCATE TABLE PAAprHdrHist
TRUNCATE TABLE PABatch
TRUNCATE TABLE PABatchHist
TRUNCATE TABLE PABilling
TRUNCATE TABLE PABillingHist
TRUNCATE TABLE PABillingInvGenDtl
TRUNCATE TABLE PABillingInvGenHdr
TRUNCATE TABLE PABillingWorkDtl
TRUNCATE TABLE PABillingWorkHdr
TRUNCATE TABLE PABillType
TRUNCATE TABLE PABudgetBucket
TRUNCATE TABLE PABudgetDtl
TRUNCATE TABLE PABudgetHdr
TRUNCATE TABLE PABudgetTrx
TRUNCATE TABLE PABudgetTrxHist
TRUNCATE TABLE PABudgetType
TRUNCATE TABLE PACompany
TRUNCATE TABLE PALaborGroup
TRUNCATE TABLE PAPhaseActivity
TRUNCATE TABLE PAPhaseActivityLog
TRUNCATE TABLE PAPhaseRevenue
TRUNCATE TABLE PAProject
TRUNCATE TABLE PAProjectLog
TRUNCATE TABLE PAProjectPhase
TRUNCATE TABLE PAProjectPhaseItem
TRUNCATE TABLE PAProjectPhaseLog
TRUNCATE TABLE PAProjectType
TRUNCATE TABLE PARate
TRUNCATE TABLE PASession
TRUNCATE TABLE PAShift
TRUNCATE TABLE PAStatus
TRUNCATE TABLE PATemplate
TRUNCATE TABLE PATemplateActivity
TRUNCATE TABLE PATransactionType
TRUNCATE TABLE PMAppVersion
TRUNCATE TABLE PMContact
TRUNCATE TABLE PMCustomer
TRUNCATE TABLE PMCustomerActivity
TRUNCATE TABLE PMCustomerActivityAudit
TRUNCATE TABLE PMCustomerAudit
TRUNCATE TABLE PMCustomerContact
TRUNCATE TABLE PMCustomerItem
TRUNCATE TABLE PMCustomerItemAudit
TRUNCATE TABLE PMCustomerLicenseDtl
TRUNCATE TABLE PMCustomerLicenseHdr
TRUNCATE TABLE PMCustomerLog
TRUNCATE TABLE PMCustomerRef
TRUNCATE TABLE PMCustomerStatus
TRUNCATE TABLE PMCustomerType
TRUNCATE TABLE PMItem
TRUNCATE TABLE PMItemCategory
TRUNCATE TABLE PMItemLicenseAttribute
TRUNCATE TABLE PMKBArticle
TRUNCATE TABLE PMKBArticleKeyword
TRUNCATE TABLE PMKeyword
TRUNCATE TABLE PMLicenseAgreement
TRUNCATE TABLE PMLicenseAttribute
TRUNCATE TABLE PMLicensePrivate
TRUNCATE TABLE PMLicenseRequest
TRUNCATE TABLE PMPlatform
TRUNCATE TABLE PMPrivate
TRUNCATE TABLE PMProduct
TRUNCATE TABLE PMRegionDtl
TRUNCATE TABLE PMRegionHdr
TRUNCATE TABLE PMRegionSecurity
TRUNCATE TABLE PMSupportDtl
TRUNCATE TABLE PMSupportHdr
TRUNCATE TABLE POAprDtl
TRUNCATE TABLE POAprDtlDistribution
TRUNCATE TABLE POAprDtlDistributionHist
TRUNCATE TABLE POAprDtlHist
TRUNCATE TABLE POAprDtlPOHeader
TRUNCATE TABLE POAprDtlPOHeaderHist
TRUNCATE TABLE POAprDtlProjectDistribution
TRUNCATE TABLE POAprDtlProjectDistributionHist
TRUNCATE TABLE POAprDtlSegment
TRUNCATE TABLE POAprDtlSegmentHist
TRUNCATE TABLE POAprDtlTax
TRUNCATE TABLE POAprDtlTaxHist
TRUNCATE TABLE POAprHdr
TRUNCATE TABLE POAprHdrHist
TRUNCATE TABLE PODetail
TRUNCATE TABLE PODetailDistribution
TRUNCATE TABLE PODetailDistributionHist
TRUNCATE TABLE PODetailHist
TRUNCATE TABLE PODetailLog
TRUNCATE TABLE PODetailLogHist
TRUNCATE TABLE PODetailProjectDistribution
TRUNCATE TABLE PODetailProjectDistributionHist
TRUNCATE TABLE PODetailSegment
TRUNCATE TABLE PODetailSegmentHist
TRUNCATE TABLE PODetailTax
TRUNCATE TABLE PODetailTaxHist
TRUNCATE TABLE POHeader
TRUNCATE TABLE POHeaderHist
TRUNCATE TABLE POHeaderLog
TRUNCATE TABLE POHeaderLogHist
TRUNCATE TABLE POSession
TRUNCATE TABLE PTIPagingHeader
TRUNCATE TABLE PTIPagingPageDetail
TRUNCATE TABLE PTIPagingPageHeader
TRUNCATE TABLE RCVAprDtl
TRUNCATE TABLE RCVAprDtlDistribution
TRUNCATE TABLE RCVAprDtlDistributionHist
TRUNCATE TABLE RCVAprDtlHist
TRUNCATE TABLE RCVAprDtlProjectDistribution
TRUNCATE TABLE RCVAprDtlProjectDistributionHist
TRUNCATE TABLE RCVAprDtlRCVHeader
TRUNCATE TABLE RCVAprDtlRCVHeaderHist
TRUNCATE TABLE RCVAprDtlSegment
TRUNCATE TABLE RCVAprDtlSegmentHist
TRUNCATE TABLE RCVAprDtlTax
TRUNCATE TABLE RCVAprDtlTaxHist
TRUNCATE TABLE RCVAprHdr
TRUNCATE TABLE RCVAprHdrHist
TRUNCATE TABLE RCVAutoRcvDtl
TRUNCATE TABLE RCVAutoRcvDtlDistribution
TRUNCATE TABLE RCVAutoRcvDtlDistributionHist
TRUNCATE TABLE RCVAutoRcvDtlHist
TRUNCATE TABLE RCVAutoRcvDtlProjectDistribution
TRUNCATE TABLE RCVAutoRcvDtlProjectDistributionHist
TRUNCATE TABLE RCVAutoRcvDtlSegment
TRUNCATE TABLE RCVAutoRcvDtlSegmentHist
TRUNCATE TABLE RCVAutoRcvHdr
TRUNCATE TABLE RCVAutoRcvHdrHist
TRUNCATE TABLE RCVAutoRetDtl
TRUNCATE TABLE RCVAutoRetDtlHist
TRUNCATE TABLE RCVAutoRetDtlTax
TRUNCATE TABLE RCVAutoRetDtlTaxHist
TRUNCATE TABLE RCVAutoRetHdr
TRUNCATE TABLE RCVAutoRetHdrHist
TRUNCATE TABLE RCVAutoRetRevDtl
TRUNCATE TABLE RCVAutoRetRevDtlHist
TRUNCATE TABLE RCVAutoRetRevDtlTax
TRUNCATE TABLE RCVAutoRetRevDtlTaxHist
TRUNCATE TABLE RCVAutoRetRevHdr
TRUNCATE TABLE RCVAutoRetRevHdrHist
TRUNCATE TABLE RCVDetail
TRUNCATE TABLE RCVDetailDistribution
TRUNCATE TABLE RCVDetailDistributionHist
TRUNCATE TABLE RCVDetailHist
TRUNCATE TABLE RCVDetailInvMatch
TRUNCATE TABLE RCVDetailInvMatchUnitPrice
TRUNCATE TABLE RCVDetailInvMatchUnitPriceReturn
TRUNCATE TABLE RCVDetailLog
TRUNCATE TABLE RCVDetailLogHist
TRUNCATE TABLE RCVDetailProjectDistribution
TRUNCATE TABLE RCVDetailProjectDistributionHist
TRUNCATE TABLE RCVDetailRCVDistribution
TRUNCATE TABLE RCVDetailRCVDistributionHist
TRUNCATE TABLE RCVDetailSegment
TRUNCATE TABLE RCVDetailSegmentHist
TRUNCATE TABLE RCVDetailTax
TRUNCATE TABLE RCVDetailTaxHist
TRUNCATE TABLE RCVDetailUnitPrice
TRUNCATE TABLE RCVDetailUnitPriceReturn
TRUNCATE TABLE RCVDistribution
TRUNCATE TABLE RCVDistributionHist
TRUNCATE TABLE RCVHeader
TRUNCATE TABLE RCVHeaderHist
TRUNCATE TABLE RCVHeaderLog
TRUNCATE TABLE RCVHeaderLogHist
TRUNCATE TABLE RCVLoadWizard
TRUNCATE TABLE RCVSession
TRUNCATE TABLE RCVType
TRUNCATE TABLE RFQVendorAssign
TRUNCATE TABLE RFQVendorQuote
TRUNCATE TABLE RFQVendorQuoteForm
TRUNCATE TABLE RFQVendorQuoteHdr
TRUNCATE TABLE RFQVendorQuotePortalAttach
TRUNCATE TABLE RFQVendorQuotePortalDtl
TRUNCATE TABLE RFQVendorQuotePortalHdr
TRUNCATE TABLE RFQVendorQuotePortalHdrWCSecurity
TRUNCATE TABLE RQAprDtl
TRUNCATE TABLE RQAprDtlDistribution
TRUNCATE TABLE RQAprDtlEXPTypeQuestionnaire
TRUNCATE TABLE RQAprDtlProjectDistribution
TRUNCATE TABLE RQAprDtlRQHeader
TRUNCATE TABLE RQAprDtlSegment
TRUNCATE TABLE RQAprDtlTax
TRUNCATE TABLE RQAprHdr
TRUNCATE TABLE RQAttachRule
TRUNCATE TABLE RQBudgetPA
TRUNCATE TABLE RQBudgetWS
TRUNCATE TABLE RQDetail
TRUNCATE TABLE RQDetailDistribution
TRUNCATE TABLE RQDetailEXPTypeQuestionnaire
TRUNCATE TABLE RQDetailLog
TRUNCATE TABLE RQDetailProjectDistribution
TRUNCATE TABLE RQDetailSegment
TRUNCATE TABLE RQDetailTax
TRUNCATE TABLE RQDetailWork
TRUNCATE TABLE RQHeader
TRUNCATE TABLE RQInvAttachHdr
TRUNCATE TABLE RQMemo
TRUNCATE TABLE RQPriority
TRUNCATE TABLE RQRevDtl
TRUNCATE TABLE RQRevDtlDistribution
TRUNCATE TABLE RQRevDtlEXPTypeQuestionnaire
TRUNCATE TABLE RQRevDtlProjectDistribution
TRUNCATE TABLE RQRevDtlRelease
TRUNCATE TABLE RQRevDtlRQHeader
TRUNCATE TABLE RQRevDtlSegment
TRUNCATE TABLE RQRevDtlTax
TRUNCATE TABLE RQRevHdr
TRUNCATE TABLE RQSession
TRUNCATE TABLE RQTemplateDtl
TRUNCATE TABLE RQTemplateDtlDistribution
TRUNCATE TABLE RQTemplateDtlSegment
TRUNCATE TABLE RQTemplateForm
TRUNCATE TABLE RQTemplateHdr
TRUNCATE TABLE RQType
TRUNCATE TABLE RQTypeLayout
TRUNCATE TABLE TEAprDtl
TRUNCATE TABLE TEAprDtlHist
TRUNCATE TABLE TEAprDtlHistTETimeSheetHdrHist
TRUNCATE TABLE TEAprDtlTETimeSheetHdr
TRUNCATE TABLE TEAprHdr
TRUNCATE TABLE TEAprHdrHist
TRUNCATE TABLE TEEarningCode
TRUNCATE TABLE TEMobileTime
TRUNCATE TABLE TERevDtl
TRUNCATE TABLE TERevHdr
TRUNCATE TABLE TESession
TRUNCATE TABLE TETimePeriod
TRUNCATE TABLE TETimeSheetDtl
TRUNCATE TABLE TETimeSheetDtlHist
TRUNCATE TABLE TETimeSheetDtlLog
TRUNCATE TABLE TETimeSheetDtlLogHist
TRUNCATE TABLE TETimeSheetDtlTimeCard
TRUNCATE TABLE TETimeSheetDtlTimeCardHist
TRUNCATE TABLE TETimeSheetDtlTimeCardVirtual
TRUNCATE TABLE TETimeSheetDtlVirtual
TRUNCATE TABLE TETimeSheetHdr
TRUNCATE TABLE TETimeSheetHdrHist
TRUNCATE TABLE TETimeTrackDtl
TRUNCATE TABLE TETimeTrackDtlHist
TRUNCATE TABLE TETimeTrackHdr
TRUNCATE TABLE TETimeTrackHdrHist
TRUNCATE TABLE TETimeType
TRUNCATE TABLE VCDetail
TRUNCATE TABLE VCHeader
TRUNCATE TABLE VCNote
TRUNCATE TABLE WCAAAllocation
TRUNCATE TABLE WCAAAllocationWork
TRUNCATE TABLE WCAADimension
TRUNCATE TABLE WCAADimensionWork
TRUNCATE TABLE WCAddress
TRUNCATE TABLE WCAppConfigSetting
TRUNCATE TABLE WCAppConnectorObject
TRUNCATE TABLE WCAppConnectorObjectLog
TRUNCATE TABLE WCAppConnectorObjectWork
TRUNCATE TABLE WCAppConnectorSetting
TRUNCATE TABLE WCAppRequiredSetting
TRUNCATE TABLE WCApprovalStatus
TRUNCATE TABLE WCAprPath
TRUNCATE TABLE WCAprPathApproved
TRUNCATE TABLE WCAttach
TRUNCATE TABLE WCAttachSync
TRUNCATE TABLE WCAuditReport
TRUNCATE TABLE WCAuditReportField
TRUNCATE TABLE WCAuditReportType
TRUNCATE TABLE WCBankType
TRUNCATE TABLE WCBatch
TRUNCATE TABLE WCBatchType
TRUNCATE TABLE WCChart
TRUNCATE TABLE WCChartPageRegion
TRUNCATE TABLE WCChartProperty
TRUNCATE TABLE WCChartPropertySetting
TRUNCATE TABLE WCChartType
TRUNCATE TABLE WCChartTypeProperty
TRUNCATE TABLE WCCountry
TRUNCATE TABLE WCCreditCardTran
TRUNCATE TABLE WCCreditCardType
TRUNCATE TABLE WCDataDictField
TRUNCATE TABLE WCDataDictHdr
TRUNCATE TABLE WCDataObject
TRUNCATE TABLE WCDept
TRUNCATE TABLE WCDeptSegment
TRUNCATE TABLE WCDIAPIQueuedOutbound
TRUNCATE TABLE WCDIAPIQueuedOutboundHist
TRUNCATE TABLE WCDIAPIXMLPacket
TRUNCATE TABLE WCDIAPIXMLPacketDtl
TRUNCATE TABLE WCDistribution
TRUNCATE TABLE WCDistributionGroupDtl
TRUNCATE TABLE WCDistributionGroupHdr
TRUNCATE TABLE WCDistributionWork
TRUNCATE TABLE WCDocument
TRUNCATE TABLE WCEAICQueue
TRUNCATE TABLE WCEAICQueueHist
TRUNCATE TABLE WCEFT
TRUNCATE TABLE WCEmailDocDtl
TRUNCATE TABLE WCEmailDocHdr
TRUNCATE TABLE WCEmailQueue
TRUNCATE TABLE WCEmailQueueSent
TRUNCATE TABLE WCFilterDtl
TRUNCATE TABLE WCFilterHdr
TRUNCATE TABLE WCFilterHdrSec
TRUNCATE TABLE WCFOB
TRUNCATE TABLE WCFormDataSource
TRUNCATE TABLE WCFormDtl
TRUNCATE TABLE WCFormHdr
TRUNCATE TABLE WCFormLayout
TRUNCATE TABLE WCFormLayoutField
TRUNCATE TABLE WCFormLayoutFieldAttribute
TRUNCATE TABLE WCFormSection
TRUNCATE TABLE WCGLBudgetPool
TRUNCATE TABLE WCGUIDLink
TRUNCATE TABLE WCICCompany
TRUNCATE TABLE WCICCompanyRel
TRUNCATE TABLE WCICCompanyTableLinkType
TRUNCATE TABLE WCImportMap
TRUNCATE TABLE WCInstall
TRUNCATE TABLE WCLanguage
TRUNCATE TABLE WCLanguageForm
TRUNCATE TABLE WCLanguageResource
TRUNCATE TABLE WCLanguageResourceD
TRUNCATE TABLE WCLanguageSQL
TRUNCATE TABLE WCLineUp
TRUNCATE TABLE WCLineUpSec
TRUNCATE TABLE WCLineUpSecAltr
TRUNCATE TABLE WCListDtl
TRUNCATE TABLE WCListHdr
TRUNCATE TABLE WCListType
TRUNCATE TABLE WCLog
TRUNCATE TABLE WCLogType
TRUNCATE TABLE WCMassUpdateDtl
TRUNCATE TABLE WCMenu
TRUNCATE TABLE WCMimeType
TRUNCATE TABLE WCMobileDeviceTableSync
TRUNCATE TABLE WCMobileSyncDataChange
TRUNCATE TABLE WCNAICS
TRUNCATE TABLE WCNameValueList
TRUNCATE TABLE WCNote
TRUNCATE TABLE WCOrganization
TRUNCATE TABLE WCPageRegion
TRUNCATE TABLE WCPaymentTerm
TRUNCATE TABLE WCPCard
TRUNCATE TABLE WCPCardPoolDtl
TRUNCATE TABLE WCPCardPoolHdr
TRUNCATE TABLE WCPCardPoolRole
TRUNCATE TABLE WCPosition
TRUNCATE TABLE WCPrimaryKey
TRUNCATE TABLE WCProcess
TRUNCATE TABLE WCRole
TRUNCATE TABLE WCRptAttachment
TRUNCATE TABLE WCRptDtl
TRUNCATE TABLE WCRptHdr
TRUNCATE TABLE WCRRGroup
TRUNCATE TABLE WCRRGroupLineUp
TRUNCATE TABLE WCRRGroupSec
TRUNCATE TABLE WCRRSecurity
TRUNCATE TABLE WCRRTemplate
TRUNCATE TABLE WCRRTemplateDtl
TRUNCATE TABLE WCRRTemplateSP
TRUNCATE TABLE WCSecAltr
TRUNCATE TABLE WCSecCalendar
TRUNCATE TABLE WCSecCreditCard
TRUNCATE TABLE WCSecDept
TRUNCATE TABLE WCSecGroup
TRUNCATE TABLE WCSecRole
TRUNCATE TABLE WCSecRpt
TRUNCATE TABLE WCSecType
TRUNCATE TABLE WCSecurity
TRUNCATE TABLE WCSecurityAccess
TRUNCATE TABLE WCSecurityAccessEffective
TRUNCATE TABLE WCSecurityAccessTemplate
TRUNCATE TABLE WCSecurityPortalCustomer
TRUNCATE TABLE WCSecuritySetting
TRUNCATE TABLE WCShippingMethod
TRUNCATE TABLE WCSIC
TRUNCATE TABLE WCSPError
TRUNCATE TABLE WCSystem
TRUNCATE TABLE WCSystemSetting
TRUNCATE TABLE WCTableAuditDtl
TRUNCATE TABLE WCTableAuditHdr
TRUNCATE TABLE WCTableFieldMaintLink
TRUNCATE TABLE WCTax
TRUNCATE TABLE WCTaxClass
TRUNCATE TABLE WCTaxClassRate
TRUNCATE TABLE WCTaxScheduleDtl
TRUNCATE TABLE WCTaxScheduleHdr
TRUNCATE TABLE WCTaxTrx
TRUNCATE TABLE WCTEMPBUDValidate
TRUNCATE TABLE WCTEMPENCEncumbranceAdjust
TRUNCATE TABLE WCTEMPEXPCalculateCreditMemo
TRUNCATE TABLE WCTEMPFNAAADefault
TRUNCATE TABLE WCTEMPFNAAAValidate
TRUNCATE TABLE WCTEMPFNAGetGLPeriod
TRUNCATE TABLE WCTEMPGLBudgetDtlTrxUpdate
TRUNCATE TABLE WCTEMPGLBudgetValidate
TRUNCATE TABLE WCTEMPGLPostingCodeAccountDtlReCalculate
TRUNCATE TABLE WCTEMPGLSegmentValidate
TRUNCATE TABLE WCTEMPGLValidate
TRUNCATE TABLE WCTEMPPAGetRate
TRUNCATE TABLE WCTEMPPAValidate
TRUNCATE TABLE WCTEMPPOValidateDtl
TRUNCATE TABLE WCTEMPPOValidateHdr
TRUNCATE TABLE WCTEMPPTIConvertCurrency
TRUNCATE TABLE WCTEMPPTIConvertCurrencyExt
TRUNCATE TABLE WCTEMPPTICurrencyRound
TRUNCATE TABLE WCTEMPRCVReturnValidate
TRUNCATE TABLE WCTEMPRCVValidateDtl
TRUNCATE TABLE WCTEMPRCVValidateHdr
TRUNCATE TABLE WCTEMPRelatedTransaction
TRUNCATE TABLE WCTEMPRQFNAValidate
TRUNCATE TABLE WCTEMPRQProjectBudgetValGRP
TRUNCATE TABLE WCTEMPRQRevLoad
TRUNCATE TABLE WCTEMPRQValidate
TRUNCATE TABLE WCTEMPRQValidateHdr
TRUNCATE TABLE WCTEMPSnapShot
TRUNCATE TABLE WCTEMPTriggerMsg
TRUNCATE TABLE WCTEMPVCDefault
TRUNCATE TABLE WCTEMPVCValidate
TRUNCATE TABLE WCTEMPWCAppConnectorObjectPaging
TRUNCATE TABLE WCTEMPWCDistCopy
TRUNCATE TABLE WCTEMPWCDistributionGroupDef
TRUNCATE TABLE WCTEMPWCDistributionRecalc
TRUNCATE TABLE WCTEMPWCDistributionTrigger
TRUNCATE TABLE WCTEMPWCTaxCalculate
TRUNCATE TABLE WCTEMPWCTaxCalculateDtl
TRUNCATE TABLE WCTEMPWCTaxCalculateExt
TRUNCATE TABLE WCTEMPWCValDtlPromoteToHeader
TRUNCATE TABLE WCTEMPWCWarnings
TRUNCATE TABLE WCTEMPWSWO
TRUNCATE TABLE WCTrackTableChanges
TRUNCATE TABLE WCTransactionLog
TRUNCATE TABLE WCUDFListDtl
TRUNCATE TABLE WCUDFListHdr
TRUNCATE TABLE WCUDFTemplateDtl
TRUNCATE TABLE WCUDFTemplateDtlValue
TRUNCATE TABLE WCUDFTemplateField
TRUNCATE TABLE WCUDFTemplateHdr
TRUNCATE TABLE WCUDFTemplateTranField
TRUNCATE TABLE WCValDtl
TRUNCATE TABLE WCVendorInfo
TRUNCATE TABLE WCVersions
TRUNCATE TABLE WCVirtualCol
TRUNCATE TABLE WCWSWO
TRUNCATE TABLE WCZoom
TRUNCATE TABLE WCZoomCondition
TRUNCATE TABLE WCZoomConditionDtl
TRUNCATE TABLE WCZoomOption
TRUNCATE TABLE WCZoomSRD
TRUNCATE TABLE WOOrderHdr
EXEC dbo.spPTIFixCalcTable 'UPDATE'
