SET FMTONLY OFF; SET NO_BROWSETABLE ON;use TWO
SET DATEFORMAT mdy
SELECT  TOP 25 dPJPHASE AS dPJPHASE, dPHASENAME AS dPHASENAME, dPHASEDESC AS dPHASEDESC
FROM PJ003 WITH (NOLOCK) INNER JOIN PJ001 WITH (NOLOCK) ON PJ001.dPJID = PJ003.dPJID   
WHERE 
dPHASESTATUS = 2 AND dPJPHASE <> '-Project-' AND PJ003.dPJID = 'IT'
 ORDER BY 1,2,3 SET NO_BROWSETABLE OFF;

 SET FMTONLY OFF; SET NO_BROWSETABLE ON;use TWO
SET DATEFORMAT mdy
SELECT  TOP 25 dPJID AS dPJID, dPJNAME AS dPJNAME, dPJDESC AS dPJDESC, CASE WHEN dALLOWPHASE = 0 THEN '-Project-' ELSE '' END AS dALLOWPHASE
FROM PJ001 WITH (NOLOCK)  
WHERE 
dPJSTATUS = 2
 ORDER BY 1,2,3 SET NO_BROWSETABLE OFF;

 select * from PJ003 

 insert into PJ001
 (dPJID ,dPJNAME,dPJDESC,dALLOWPHASE,dPJSTATUS)
 VALUES
 ('IT','IT-ADMIN','IT Admin','1',2)

 
  insert into PJ003
  ( dPJPHASE, dPHASENAME,dPHASEDESC,dPHASESTATUS,dPJID)
  VALUES 
  ('HAREDWARE','001-HARDWARE','HARDWARE',2,'IT')

