--delete from EXPExpenseSheetDtl where idfImportedRefNo<>''
select idfPTICurrencyKey from EXPExpenseSheetDtl
select idfWCSecurityKey,* from EXPCreditCard
select * from EXPType
select * from WCDept
select idfSecurityId,* from WCSecurity
update EXPCreditCard set idfEXPTypeKey=13 where idfEXPTypeKey=2
update EXPCreditCard set idfEXPTypeKey=14 where idfEXPTypeKey=3
update EXPCreditCard set idfEXPTypeKey=15 where idfEXPTypeKey=4
update EXPCreditCard set idfEXPTypeKey=16 where idfEXPTypeKey=5
update EXPCreditCard set idfEXPTypeKey=17 where idfEXPTypeKey=6
update EXPCreditCard  set idfPTICurrencyKey=5,idfWCDeptKey=3
UpDATE EXPCreditCard   set idfWCSecurityKey=3 where idfWCSecurityKey=1
UpDATE EXPCreditCard  set idfWCSecurityKey=4 where idfWCSecurityKey=2
insert into EXPCreditCard ([idfAmtExtended]
           ,[idfComment]
           ,[idfDay]
           ,[idfDescription]
           ,[idfImportedRefNo]
           ,[idfPrice]
           ,[idfQuantity]
           ,[idfDateCreated]
           ,[idfDateModified]
           ,[idfUserCreated]
           ,[idfUserModified]
           ,[idfEXPExpenseSheetDtlKey]
           ,[idfEXPPaymentKey]
           ,[idfEXPTypeKey]
           ,[idfGLAccountKey]
           ,[idfPABillTypeKey]
           ,[idfPAPhaseActivityKey]
           ,[idfPAProjectKey]
           ,[idfPAProjectPhaseKey]
           ,[idfPTICurrencyKey]
           ,[idfWCCountryKey]
           ,[idfWCDeptKey]
           ,[idfWCICCompanyKeySource]
           ,[idfWCImportMapKey]
           ,[idfWCSecurityKey]
           ,[idfWCShippingMethodKey]
           ,[idfWCTaxScheduleHdrKey]
           ,[udfDateField01]
           ,[udfDateField02]
           ,[udfDateField03]
           ,[udfDateField04]
           ,[udfDateField05]
           ,[udfLargeTextField01]
           ,[udfLargeTextField02]
           ,[udfLargeTextField03]
           ,[udfNumericField01]
           ,[udfNumericField02]
           ,[udfNumericField03]
           ,[udfNumericField04]
           ,[udfNumericField05]
           ,[udfNumericField06]
           ,[udfNumericField07]
           ,[udfNumericField08]
           ,[udfNumericField09]
           ,[udfNumericField10]
           ,[udfTextField01]
           ,[udfTextField02]
           ,[udfTextField03]
           ,[udfTextField04]
           ,[udfTextField05]
           ,[udfTextField06]
           ,[udfTextField07]
           ,[udfTextField08]
           ,[udfTextField09]
           ,[udfTextField10])

select        [idfAmtExtended]
           ,[idfComment]
           ,[idfDay]
           ,[idfDescription]
           ,[idfImportedRefNo]
           ,[idfPrice]
           ,[idfQuantity]
           ,[idfDateCreated]
           ,[idfDateModified]
           ,[idfUserCreated]
           ,[idfUserModified]
           ,[idfEXPExpenseSheetDtlKey]
           ,[idfEXPPaymentKey]
           ,[idfEXPTypeKey]
           ,[idfGLAccountKey]
           ,[idfPABillTypeKey]
           ,[idfPAPhaseActivityKey]
           ,[idfPAProjectKey]
           ,[idfPAProjectPhaseKey]
           ,[idfPTICurrencyKey]
           ,[idfWCCountryKey]
           ,[idfWCDeptKey]
           ,[idfWCICCompanyKeySource]
           ,[idfWCImportMapKey]
           ,[idfWCSecurityKey]
           ,[idfWCShippingMethodKey]
           ,[idfWCTaxScheduleHdrKey]
           ,[udfDateField01]
           ,[udfDateField02]
           ,[udfDateField03]
           ,[udfDateField04]
           ,[udfDateField05]
           ,[udfLargeTextField01]
           ,[udfLargeTextField02]
           ,[udfLargeTextField03]
           ,[udfNumericField01]
           ,[udfNumericField02]
           ,[udfNumericField03]
           ,[udfNumericField04]
           ,[udfNumericField05]
           ,[udfNumericField06]
           ,[udfNumericField07]
           ,[udfNumericField08]
           ,[udfNumericField09]
           ,[udfNumericField10]
           ,[udfTextField01]
           ,[udfTextField02]
           ,[udfTextField03]
           ,[udfTextField04]
           ,[udfTextField05]
           ,[udfTextField06]
           ,[udfTextField07]
           ,[udfTextField08]
           ,[udfTextField09]
           ,[udfTextField10]
from TWO..EXPCreditCard