insert into TX00101 (TAXSCHID,TXSCHDSC) values ('ALL-PURCHASES','All GST Purchases Details')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('ALL-SALES','All GST Sales Details')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTTSCAP','GST Exc.Taxable Supply-Capital')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTADJ','GST Excl. Adjustment')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('S-GSTADJ','GST Excl. Adjustment')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('S-GSTEX','GST Excl. Exports')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTFS','GST Excl. Free Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('S-GSTFS','GST Excl. Free Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTIMPCUST','GST Excl. Import Customs')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTIMPSUP','GST Excl. Import Supplier')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTIT','GST Excl. Input Taxed')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('S-GSTIT','GST Excl. Input Taxed Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTNITD','GST Excl. Non Tax Deductible')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('P-GSTTS','GST Excl. Taxable Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('S-GSTTS','GST Excl. Taxable Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTTSCAP','GST Inc.Taxable Supply-Capital')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTNITD','GST Incl. - NITD')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTADJ','GST Incl. Adjustment')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('SI-GSTADJ','GST Incl. Adjustment')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('SI-GSTEX','GST Incl. Exports')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTFS','GST Incl. Free Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('SI-GSTFS','GST Incl. Free Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTIT','GST Incl. Input Taxed Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('SI-GSTIT','GST Incl. Input Taxed Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('PI-GSTTS','GST Incl. Taxable Supply')
insert into TX00101 (TAXSCHID,TXSCHDSC) values ('SI-GSTTS','GST Incl. Taxable Supply')


USE [TSTAU]
GO
SET IDENTITY_INSERT [dbo].[TX00101] ON 
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'ALL-SALES      ', N'All GST Sales Details          ', CAST(0.00000 AS Numeric(19, 5)), 1)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'ALL-PURCHASES  ', N'All GST Purchases Details      ', CAST(0.00000 AS Numeric(19, 5)), 2)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTADJ       ', N'GST Excl. Adjustment           ', CAST(0.00000 AS Numeric(19, 5)), 3)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTFS        ', N'GST Excl. Free Supply          ', CAST(0.00000 AS Numeric(19, 5)), 4)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTIMPCUST   ', N'GST Excl. Import Customs       ', CAST(0.00000 AS Numeric(19, 5)), 5)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTIMPSUP    ', N'GST Excl. Import Supplier      ', CAST(0.00000 AS Numeric(19, 5)), 6)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTIT        ', N'GST Excl. Input Taxed          ', CAST(0.00000 AS Numeric(19, 5)), 7)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTNITD      ', N'GST Excl. Non Tax Deductible   ', CAST(0.00000 AS Numeric(19, 5)), 8)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTTS        ', N'GST Excl. Taxable Supply       ', CAST(0.00000 AS Numeric(19, 5)), 9)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'P-GSTTSCAP     ', N'GST Exc.Taxable Supply-Capital ', CAST(0.00000 AS Numeric(19, 5)), 10)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTADJ      ', N'GST Incl. Adjustment           ', CAST(0.00000 AS Numeric(19, 5)), 11)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTFS       ', N'GST Incl. Free Supply          ', CAST(0.00000 AS Numeric(19, 5)), 12)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTIT       ', N'GST Incl. Input Taxed Supply   ', CAST(0.00000 AS Numeric(19, 5)), 13)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTNITD     ', N'GST Incl. - NITD               ', CAST(0.00000 AS Numeric(19, 5)), 14)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTTS       ', N'GST Incl. Taxable Supply       ', CAST(0.00000 AS Numeric(19, 5)), 15)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'PI-GSTTSCAP    ', N'GST Inc.Taxable Supply-Capital ', CAST(0.00000 AS Numeric(19, 5)), 16)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'S-GSTADJ       ', N'GST Excl. Adjustment           ', CAST(0.00000 AS Numeric(19, 5)), 17)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'S-GSTEX        ', N'GST Excl. Exports              ', CAST(0.00000 AS Numeric(19, 5)), 18)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'S-GSTFS        ', N'GST Excl. Free Supply          ', CAST(0.00000 AS Numeric(19, 5)), 19)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'S-GSTIT        ', N'GST Excl. Input Taxed Supply   ', CAST(0.00000 AS Numeric(19, 5)), 20)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'S-GSTTS        ', N'GST Excl. Taxable Supply       ', CAST(0.00000 AS Numeric(19, 5)), 21)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'SI-GSTADJ      ', N'GST Incl. Adjustment           ', CAST(0.00000 AS Numeric(19, 5)), 22)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'SI-GSTEX       ', N'GST Incl. Exports              ', CAST(0.00000 AS Numeric(19, 5)), 23)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'SI-GSTFS       ', N'GST Incl. Free Supply          ', CAST(0.00000 AS Numeric(19, 5)), 24)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'SI-GSTIT       ', N'GST Incl. Input Taxed Supply   ', CAST(0.00000 AS Numeric(19, 5)), 25)
GO
INSERT [dbo].[TX00101] ([TAXSCHID], [TXSCHDSC], [NOTEINDX], [DEX_ROW_ID]) VALUES (N'SI-GSTTS       ', N'GST Incl. Taxable Supply       ', CAST(0.00000 AS Numeric(19, 5)), 26)
GO
SET IDENTITY_INSERT [dbo].[TX00101] OFF
GO
SET IDENTITY_INSERT [dbo].[TX00201] ON 
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTADJ       ', N'GST Excl. Adjustment           ', 2, 5561, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00200000, 0, CAST(0.00000 AS Numeric(19, 5)), 1)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTFS        ', N'GST Excl. Free Supply          ', 2, 5561, N'           ', 3, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00050000, 0, CAST(0.00000 AS Numeric(19, 5)), 2)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTIMPCUST   ', N'GST Excl. Import Customs       ', 2, 5561, N'           ', 2, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00000000, 0, CAST(0.00000 AS Numeric(19, 5)), 3)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTIMPSUP    ', N'GST Excl. Import Supplier      ', 2, 5561, N'           ', 3, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00110000, 0, CAST(0.00000 AS Numeric(19, 5)), 4)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTIT        ', N'GST Excl. Input Taxed          ', 2, 5561, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 2, 0x00030000, 0, CAST(0.00000 AS Numeric(19, 5)), 5)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTNITD      ', N'GST Excl. Non Tax Deductible   ', 2, 5561, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 2, 0x00090000, 0, CAST(0.00000 AS Numeric(19, 5)), 6)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTTS        ', N'GST Excl. Taxable Supply       ', 2, 5561, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00110000, 0, CAST(0.00000 AS Numeric(19, 5)), 7)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'P-GSTTSCAP     ', N'GST Exc.Taxable Supply-Capital ', 2, 5561, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x80100000, 0, CAST(0.00000 AS Numeric(19, 5)), 8)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTADJ      ', N'GST Incl. Adjustment           ', 2, 5561, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00200000, 0, CAST(0.00000 AS Numeric(19, 5)), 9)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTFS       ', N'GST Incl. Free Supply          ', 2, 5561, N'           ', 1, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00050000, 0, CAST(0.00000 AS Numeric(19, 5)), 10)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTIT       ', N'GST Incl. Input Taxed Supply   ', 2, 5561, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 2, 0x00030000, 0, CAST(0.00000 AS Numeric(19, 5)), 11)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTNITD     ', N'GST Incl. - NITD               ', 2, 5561, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 2, 0x00090000, 0, CAST(0.00000 AS Numeric(19, 5)), 12)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTTS       ', N'GST Incl. Taxable Supply       ', 2, 5561, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x00110000, 0, CAST(0.00000 AS Numeric(19, 5)), 13)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'PI-GSTTSCAP    ', N'GST Inc.Taxable Supply-Capital ', 2, 5561, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x80100000, 0, CAST(0.00000 AS Numeric(19, 5)), 14)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'S-GSTADJ       ', N'GST Excl. Adjustment           ', 1, 5560, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x20000000, 0, CAST(0.00000 AS Numeric(19, 5)), 15)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'S-GSTEX        ', N'GST Excl. Exports              ', 1, 5560, N'           ', 3, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x03000000, 0, CAST(0.00000 AS Numeric(19, 5)), 16)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'S-GSTFS        ', N'GST Excl. Free Supply          ', 1, 5560, N'           ', 3, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x05000000, 0, CAST(0.00000 AS Numeric(19, 5)), 17)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'S-GSTIT        ', N'GST Excl. Input Taxed Supply   ', 1, 5560, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x09000000, 0, CAST(0.00000 AS Numeric(19, 5)), 18)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'S-GSTTS        ', N'GST Excl. Taxable Supply       ', 1, 5560, N'           ', 3, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 1, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x11000000, 0, CAST(0.00000 AS Numeric(19, 5)), 19)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'SI-GSTADJ      ', N'GST Incl. Adjustment           ', 1, 5560, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x20000000, 0, CAST(0.00000 AS Numeric(19, 5)), 20)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'SI-GSTEX       ', N'GST Incl. Exports              ', 1, 5560, N'           ', 1, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x03000000, 0, CAST(0.00000 AS Numeric(19, 5)), 21)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'SI-GSTFS       ', N'GST Incl. Free Supply          ', 1, 5560, N'           ', 1, CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x05000000, 0, CAST(0.00000 AS Numeric(19, 5)), 22)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'SI-GSTIT       ', N'GST Incl. Input Taxed Supply   ', 1, 5560, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x09000000, 0, CAST(0.00000 AS Numeric(19, 5)), 23)
GO
INSERT [dbo].[TX00201] ([TAXDTLID], [TXDTLDSC], [TXDTLTYP], [ACTINDX], [TXIDNMBR], [TXDTLBSE], [TXDTLPCT], [TXDTLAMT], [TDTLRNDG], [TXDBODTL], [TDTABMIN], [TDTABMAX], [TDTAXMIN], [TDTAXMAX], [TDRNGTYP], [TXDTQUAL], [TDTAXTAX], [TXDTLPDC], [TXDTLPCH], [TXDXDISC], [CMNYTXID], [NOTEINDX], [NAME], [CNTCPRSN], [ADDRESS1], [ADDRESS2], [ADDRESS3], [CITY], [STATE], [ZIPCODE], [COUNTRY], [PHONE1], [PHONE2], [PHONE3], [FAX], [TXUSRDF1], [TXUSRDF2], [VATREGTX], [TaxInvReqd], [TaxPostToAcct], [TaxBoxes], [IGNRGRSSAMNT], [TDTABPCT], [DEX_ROW_ID]) VALUES (N'SI-GSTTS       ', N'GST Incl. Taxable Supply       ', 1, 5560, N'           ', 1, CAST(10.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 2, N'               ', CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), CAST(0.00000 AS Numeric(19, 5)), 1, 0, 0, 1, N' ', 0, N'               ', CAST(0.00000 AS Numeric(19, 5)), N'                               ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                                             ', N'                                   ', N'                             ', N'           ', N'                                                             ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', N'                     ', 0, 0, 1, 0x11000000, 0, CAST(0.00000 AS Numeric(19, 5)), 24)
GO
SET IDENTITY_INSERT [dbo].[TX00201] OFF
GO
