SELECT * 
from SY00500 SY (NOLOCK)
INNER JOIN 
(SELECT BACHNUMB,SUM(DOCAMNT) TOTAMT ,COUNT(1) TOTCOUNT
from PM10000 (NOLOCK)
GROUP BY BACHNUMB) PY on SY.BACHNUMB=PY.BACHNUMB
WHERE BCHTOTAL<>TOTAMT OR NUMOFTRX<>TOTCOUNT

UPDATE SY set NUMOFTRX=TOTCOUNT,BCHTOTAL=TOTAMT
from SY00500 SY (NOLOCK)
INNER JOIN 
(SELECT BACHNUMB,SUM(DOCAMNT) TOTAMT ,COUNT(1) TOTCOUNT
from PM10000 (NOLOCK)
GROUP BY BACHNUMB) PY on SY.BACHNUMB=PY.BACHNUMB
WHERE BCHTOTAL<>TOTAMT OR NUMOFTRX<>TOTCOUNT