--Run on Control Database
UPDATE WPEControl..PTICurrency Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WPEControl..PTICurrencyAccess Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WPEControl..PTICurrencyRateHdr Set idfPTICurrencyKeyFrom =5 WHERE idfPTICurrencyKeyFrom=7
UPDATE WPEControl..PTICurrencyRateHdr Set idfPTICurrencyKeyTo =5 WHERE idfPTICurrencyKeyTo=7

-- Run on Company Databaes
UPDATE APAutoPaymentHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APAutoPaymentHdrHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APPaymentHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APPaymentHdrHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APVendor Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APVendorAprDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APVendorAprDtlHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE APVoucher Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE ARInvoiceHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtl Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPAprDtlAttendee Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlAttendeeHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlHist Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPAprDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplit Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplit Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPAprDtlSplitAttendee Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplitAttendeeHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplitHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplitHist Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPAprDtlSplitProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPAprDtlSplitProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPCreditCard Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPCreditCardHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtl Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPExpenseSheetDtlAttendee Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlAttendeeHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlHist Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPExpenseSheetDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplit Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplit Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPExpenseSheetDtlSplitAttendee Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplitAttendeeHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplitHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplitHist Set idfPTICurrencyKeyReceipt =5 WHERE idfPTICurrencyKeyReceipt=7
UPDATE EXPExpenseSheetDtlSplitProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPExpenseSheetDtlSplitProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPMobileExpense Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE EXPTypeCountry Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE GLJournalDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE GLJournalHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE IVItemPrecision Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE IVItemVendor Set idfPTICurrencyKeyPriceLast =5 WHERE idfPTICurrencyKeyPriceLast=7
UPDATE PABilling Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE PABilling Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE PABillingHist Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE PABillingHist Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE PABudgetTrx Set idfPTICurrencyKeyAmount =5 WHERE idfPTICurrencyKeyAmount=7
UPDATE PABudgetTrxHist Set idfPTICurrencyKeyAmount =5 WHERE idfPTICurrencyKeyAmount=7
UPDATE PAPhaseActivity Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PAProject Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PAProjectPhase Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PARate Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE PARate Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE PMCustomer Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE PMCustomerAudit Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE POAprDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POAprDtlDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POAprDtlPOHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POAprDtlPOHeaderHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POAprDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POAprDtlProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PODetailDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PODetailDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PODetailProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE PODetailProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE POHeaderHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlRCVHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAprDtlRCVHeaderHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAutoRcvDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAutoRcvDtlDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAutoRcvDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVAutoRcvDtlProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDetailDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDetailDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDetailProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDetailProjectDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVDistributionHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RCVHeaderHist Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQAprDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQAprDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQAprDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQAprDtlRQHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQDetail Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQDetailDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQDetailProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQDetailWork Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQMobileRequisition Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQRevDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQRevDtlDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQRevDtlProjectDistribution Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQRevDtlRQHeader Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE RQTemplateDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE TEAprDtl Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TEAprDtl Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE TEAprDtlHist Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TEAprDtlHist Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE TEMobileTime Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TEMobileTime Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE TETimeSheetDtl Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TETimeSheetDtl Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE TETimeSheetDtlHist Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TETimeSheetDtlHist Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE TETimeSheetDtlVirtual Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE TETimeSheetDtlVirtual Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE WCTEMPEXPCalculateCreditMemo Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPPAGetRate Set idfPTICurrencyKeyBill =5 WHERE idfPTICurrencyKeyBill=7
UPDATE WCTEMPPAGetRate Set idfPTICurrencyKeyCost =5 WHERE idfPTICurrencyKeyCost=7
UPDATE WCTEMPPOValidateDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPPOValidateHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPPTIConvertCurrency Set idfPTICurrencyKeyFrom =5 WHERE idfPTICurrencyKeyFrom=7
UPDATE WCTEMPPTIConvertCurrency Set idfPTICurrencyKeyTo =5 WHERE idfPTICurrencyKeyTo=7
UPDATE WCTEMPPTIConvertCurrencyExt Set idfPTICurrencyKeyFrom =5 WHERE idfPTICurrencyKeyFrom=7
UPDATE WCTEMPPTICurrencyRound Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPRCVValidateDtl Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPRCVValidateHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPRQFNAValidate Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPRQValidate Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPRQValidateHdr Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPWCDistributionGroupDef Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7
UPDATE WCTEMPWCTaxCalculate Set idfPTICurrencyKey =5 WHERE idfPTICurrencyKey=7